#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 23 18:11:43 2021

@author: julie
"""
import geopandas as gpd
# import fiona

bike_routes = gpd.read_file('nyc_bike_routes_2017.shp')